
package com.microsoft.ai108;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Ai108Service", targetNamespace = "http://ai108.microsoft.com", wsdlLocation = "http://localhost:12345/toto/titi.ai108?wsdl")
public class Ai108Service
    extends Service
{

    private final static URL AI108SERVICE_WSDL_LOCATION;
    private final static WebServiceException AI108SERVICE_EXCEPTION;
    private final static QName AI108SERVICE_QNAME = new QName("http://ai108.microsoft.com", "Ai108Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:12345/toto/titi.ai108?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AI108SERVICE_WSDL_LOCATION = url;
        AI108SERVICE_EXCEPTION = e;
    }

    public Ai108Service() {
        super(__getWsdlLocation(), AI108SERVICE_QNAME);
    }

    public Ai108Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AI108SERVICE_QNAME, features);
    }

    public Ai108Service(URL wsdlLocation) {
        super(wsdlLocation, AI108SERVICE_QNAME);
    }

    public Ai108Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AI108SERVICE_QNAME, features);
    }

    public Ai108Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ai108Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Ai108IService
     */
    @WebEndpoint(name = "Ai108Port")
    public Ai108IService getAi108Port() {
        return super.getPort(new QName("http://ai108.microsoft.com", "Ai108Port"), Ai108IService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ai108IService
     */
    @WebEndpoint(name = "Ai108Port")
    public Ai108IService getAi108Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ai108.microsoft.com", "Ai108Port"), Ai108IService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AI108SERVICE_EXCEPTION!= null) {
            throw AI108SERVICE_EXCEPTION;
        }
        return AI108SERVICE_WSDL_LOCATION;
    }

}
