INSERT INTO `user` (id, name, surname, login, password) VALUES (1, 'Toto', 'de Toto', 'toto', 'toto');
INSERT INTO `user` (id, name, surname, login, password) VALUES (2, 'Tata', 'de Tata', 'tata', 'tata');
INSERT INTO `cat` (id, name, race, birth, photo, user_id) VALUES (1, 'Klong', 'Calico', '2019-01-02', 'klong.png', 1);
INSERT INTO `cat` (id, name, race, birth, photo, user_id) VALUES (2, 'Zoubir', 'Persan', '2018-02-03', 'zoubir.png', 1);
INSERT INTO `cat` (id, name, race, birth, photo, user_id) VALUES (3, 'Zoro', 'Européen', '2017-11-02', 'zoro.png', 2);
INSERT INTO `cat` (id, name, race, birth, photo, user_id) VALUES (4, 'Maya', 'Main Coon', '2015-01-02', 'maya.png', 2);
INSERT INTO `toy` (id, libelle, couleur, cat_id) VALUES (1, 'baballe', 'hotpink', 1);
INSERT INTO `toy` (id, libelle, couleur, cat_id) VALUES (2, 'souris', 'grise', 1);
INSERT INTO `toy` (id, libelle, couleur, cat_id) VALUES (3, 'arbre à chat', 'gris', 2);
INSERT INTO `toy` (id, libelle, couleur, cat_id) VALUES (4, 'plume', 'blanche', 2);
INSERT INTO `toy` (id, libelle, couleur, cat_id) VALUES (5, 'carton', 'rose', 3);
INSERT INTO `toy` (id, libelle, couleur, cat_id) VALUES (6, 'griffoir', 'bleu ciel', 3);
INSERT INTO `toy` (id, libelle, couleur, cat_id) VALUES (7, 'plumeau', 'rouge', 4);
INSERT INTO `toy` (id, libelle, couleur, cat_id) VALUES (8, 'canard', 'jaune', 4);